### ISSUE TITLE
Proposal for a new merchant: `AutonomVie`

### ISSUE THREAD

**Issue by Unbanked0** [Unbanked0/bank_exit#11]
A new proposition for a merchant has been submitted. Please take a look and add it to OpenStreetMap if relevant:

```yaml
---
name: AutonomVie
category: Atelier
other_category: ''
street: Quily
postcode: '56230'
city: QUESTEMBERT
country: France
phone: ''
website: https://autonomvie.org
description: "Ateliers pour apprendre l'autosuffisance et devenir autonome !\r\nQue
  vous cherchiez à développer de nouvelles compétences, à explorer des passions ou
  à vous perfectionner, vous trouverez l’atelier parfait pour vous.\r\nThèmes proposés
  : habitat, alimentaire, santé, animaux, géobiologie, souveraineté."
coins:
- bitcoin
- monero
- june
ask_kyc: false
contact_facebook: ''
contact_twitter: ''
contact_telegram: "@MarieEquily"
contact_signal: ''
contact_session: ''
contact_tripadvisor: ''
contact_matrix: ''
contact_jabber: ''
contact_youtube: ''
contact_linkedin: ''
contact_instagram: ''
contact_tiktok: ''
contact_odysee: ''
delivery: false
delivery_zone: ''

```

---

*Note: this issue has been automatically opened from bank-exit website using the Github API.*
