### ISSUE TITLE
Proposal for a new merchant: `Asatru Records`

### ISSUE THREAD

**Issue by Unbanked0** [Unbanked0/bank_exit#12]
A new proposition for a merchant has been submitted. Please take a look and add it to OpenStreetMap if relevant:

```yaml
---
name: Asatru Records
category: Online Store
other_category: ''
street: Seestrasse 353
postcode: '8038'
city: Zürich
country: Switzerland
phone: ''
website: https://www.asatru-records.com/
description: "Asatru Records is a former record company of Pagan Metal and Viking
  Metal bands and is today mainly an online store for merchandising articles from
  the fields of Heavy Metal, Death Metal, Viking Metal, Black Metal and Viking mythology.
  But there are also other great motifs for Bitcoin and Monero fans.\r\n\r\nLots of
  great clothes and mugs - also with political and crypto designs.\r\nFast worldwide
  delivery and good email support that responds quickly. Various cryptocurrencies
  are supported, not just Monero and Bitcoin."
coins:
- bitcoin
- monero
ask_kyc: false
contact_facebook: ''
contact_twitter: ''
contact_telegram: ''
contact_signal: ''
contact_session: ''
contact_tripadvisor: ''
contact_matrix: ''
contact_jabber: ''
contact_youtube: ''
contact_linkedin: ''
contact_instagram: ''
contact_tiktok: ''
contact_odysee: ''
delivery: false
delivery_zone: ''

```

---

*Note: this issue has been automatically opened from bank-exit website using the Github API.*
