### ISSUE TITLE
Proposal for a new merchant: `L'ATOUT BRICOLEUR`

### ISSUE THREAD

**Issue by Unbanked0** [Unbanked0/bank_exit#16]
A new proposition for a merchant has been submitted. Please take a look and add it to OpenStreetMap if relevant:

```yaml
---
name: L'ATOUT BRICOLEUR
category: Bricolage et multi-services
other_category: Bricolage et multi-services
street: 6, rue Rouget de Lisle
postcode: '11150'
city: VILLEPINTE
country: France
phone: '0670177968'
website: https://www.latoutbricoleur.com/
description: Bricolage à domicile, Travaux multi-services et entretien de jardin.
  Intervention uniquement sur devis validé et gratuit Intervention à 15km autour de
  Castelnaudary (plus loin à confirmer)
coins:
- bitcoin
- monero
- contact_less
ask_kyc: false
contact_facebook: ''
contact_twitter: ''
contact_telegram: ''
contact_signal: ''
contact_session: ''
contact_tripadvisor: ''
contact_matrix: ''
contact_jabber: ''
contact_youtube: ''
contact_linkedin: ''
contact_instagram: ''
contact_tiktok: ''
contact_odysee: ''
delivery: false
delivery_zone: ''
last_survey_on: 2025-06-20

```

---

*Note: this issue has been automatically opened from bank-exit website using the Github API.*
