### ISSUE TITLE
Proposal for a new merchant: `212 Contracting Services`

### ISSUE THREAD

**Issue by Unbanked0** [Unbanked0/bank_exit#8]
A new proposition for a merchant has been submitted. Please take a look and add it to OpenStreetMap if relevant:

```yaml
---
name: 212 Contracting Services
category: Construction company
other_category: ''
street: C/o 702 township road 219 west
postcode: '43311'
city: Bellefontaine
country: United States
phone: '019379351709'
website: https://212cs.com/
description: Home remodeling, home repairs, general contracting
coins:
- bitcoin
- monero
- gold
- silver
ask_kyc: false
contact_facebook: ''
contact_twitter: ''
contact_telegram: ''
contact_signal: https://signal.me/#eu/MGPn-WONLy8y5_xh0WHQ6eJmmyOofuAtLaLhHMfgIogIZJrmU61CaIdLb4KhqogW
contact_session: ''
contact_tripadvisor: ''
contact_matrix: ''
contact_jabber: ''
contact_youtube: ''
contact_linkedin: ''
contact_instagram: ''
contact_tiktok: ''
contact_odysee: ''
delivery: false
delivery_zone: ''

```

---

*Note: this issue has been automatically opened from bank-exit website using the Github API.*
